server:
    port: 8080
spring:
    datasource:
        driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
        url: jdbc:log4jdbc:mariadb://localhost:3306/practice?characterEncoding=UTF-8&serverTimezone=UTC
        username: root
        password: 134268aa
    devtools:
        livereload:
            enabled: true
    servlet:
        multipart:
            max-file-size: 10240MB
            max-request-size: 10240MB
            enabled: true
mybatis:
    config: mybatis-config.xml
    mapper-locations: classpath:sqlmap/**/*.xml

upload:
    downloadpath: C:\Users\user\Desktop\mypractice\downloadfile