server:
    port: 8080
spring:
    datasource:
        driver-class-name: org.mariadb.jdbc.Driver
        url: jdbc:mariadb://127.0.0.1:3306/practice?characterEncoding=UTF-8&serverTimezone=UTC&useSSL=false
        username: root
        password: 134268aa
    servlet:
        multipart:
            max-file-size: 10240MB
            max-request-size: 10240MB
            enabled: true
    mail:
        host: smtp.gmail.com
        port: 587
        username: dfsadsfdf@gamil.com
        password: tpkeaxpyfjqapuzb
        properties:
            mail:
                smtp:
                    auth: true
                    starttls:
                        enable: true
                        required: true
            default-encoding: UTF-8
    config:
        activate:
            on-profile: prod
mybatis:
    config: mybatis-config.xml
    mapper-locations: classpath:sqlmap/**/*.xml

upload:
    downloadpath: C:\Users\user\Desktop\mypractice\downloadfile